### PR TITLE
Add "encode => true" to alt and caption fields

### PR DESCRIPTION
**Pull request by goldenapples**
Since Shortcake added support for URL-encoding attribute values (https://github.com/wp-shortcake/shortcake/pull/496), we can remove the unfriendly admonitions to avoid using quote marks, branckets, or HTML in the alt and caption fields here by passing "encode" => true in the attribute registration.

#42

### CODE REVIEW

**Comment by goldenapples** [comment]
@danielbachhuber #reviewmerge?

**Comment by danielbachhuber** [comment]
@goldenapples build fail-y

**Comment by danielbachhuber** [comment]
Looks good otherwise.

**Comment by goldenapples** [comment]
Ugh. Not as simple as I was thinking. `shortcode_atts()`, which I was trying to use here in order to make use of the built-in attribute decoding, requires you to specify the full whitelist of allowed attributes, which if hardcoded would probably break a lot of expected extensibility. I think we should be able to build the defaults from the UI registration args, but I'll need to add some test cases to make sure I'm not breaking anything.

**Comment by goldenapples** [comment]
Actually, not so tricky at all - fixed in f250552.

**Pull request merged**
